# Basic settings
title: Waste My Time
description: A brief description of your site.
theme: jekyll-theme-cayman

# Repository settings (for GitHub Pages)
repository: agabor/waste-my-time

# Social links
github_username: agabor

# Show your site's title in the header
show_title: true

# Enable Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Markdown settings
markdown: kramdown

# Set default values for the pages
defaults:
  - scope:
      path: "" # empty string means all files in the project
    values:
      layout: default

# Plugins (if needed, optional)
plugins:
  - jekyll-feed # For RSS feed support
  - jekyll-sitemap # For generating a sitemap
