#!/bin/bash

show_help() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] <website> <minutes>

Options:
  -h, --help      Show this help message and exit
  -l, --list      List all blocked domains
  -u, --unblock   Unblock the specified website
  -r, --update    Update Pause Timer

Examples:
  $(basename "$0") facebook.com 10
  $(basename "$0") --list
  $(basename "$0") --unblock facebook.com
  $(basename "$0") --update
EOF
    exit 0
}

list_blocked_domains() {
    grep 0.0.0.0 /etc/hosts | awk '{ print $2 }'
    exit 0
}

update() {
    BASE_URL="https://pausetimer.com/src/"
    DEST_DIR="/usr/local/bin"
    sudo curl -o "$DEST_DIR/pausetimer" "$BASE_URL/pausetimer"
    echo
    sudo curl -o "$DEST_DIR/pausetimer-sync" "$BASE_URL/pausetimer-sync"
    sudo chmod +x "$DEST_DIR/pausetimer"
    sudo chmod +x "$DEST_DIR/pausetimer-sync"
    echo
    echo "Pause Timer update complete."
    exit 0
}


for arg in "$@"; do
    case "$arg" in
        --help) show_help;;
        --list) list_blocked_domains;;
        --unblock) sudo pausetimer-sync "$2" "u"; exit 0;;
        --update) update;;
    esac
done

while getopts "hlur" flag; do
    case "${flag}" in
        h) show_help;;
        l) list_blocked_domains;;
        u) sudo pausetimer-sync "$2" "u"; exit 0;;
        r) update;;
    esac
done

shift $((OPTIND-1))

if [ $# -lt 2 ]; then
   show_help
fi

sudo echo

sudo nohup sudo pausetimer-sync "$1" "$2" 2>&1 | tee &