#!/bin/bash

show_help() {
    cat << EOF
Usage: $(basename "$0") [OPTIONS] <website> <minutes>

Options:
  -h, --help    Show this help message and exit

Examples:
  $(basename "$0") facebook.com 10
EOF
    exit 1
}

for arg in "$@"; do
    case "$arg" in
        --help) show_help;;
    esac
done

while getopts "h" flag; do
    case "${flag}" in
        h) show_help;;
    esac
done

shift $((OPTIND-1))

if [ $# -lt 2 ]; then
   show_help
fi

sudo echo

sudo nohup sudo waste-time-sync "$1" "$2" 2>&1 | tee &